=== Eddy32/DAW-TPC1/TPC2/ProjRec.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ProjRec (tituloP,cabeçalho,equipa,resumo,projetos,data)>
<!ELEMENT tituloP (#PCDATA)>
<!ELEMENT cabeçalho (nome,titulo, subtitulo, dataI,dataF,supervisor)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT subtitulo (#PCDATA)>
<!ELEMENT dataI (#PCDATA)>
<!ELEMENT dataF (#PCDATA)>
<!ELEMENT supervisor (#PCDATA)>
<!ELEMENT equipa (colaborador)+>
<!ELEMENT colaborador (nomeP, numero?, email, github?)>
<!ELEMENT nomeP (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT github (#PCDATA)>
<!ELEMENT resumo (paragrafo)+>
<!ELEMENT paragrafo (#PCDATA|url)*>
<!ELEMENT url (#PCDATA)>
<!ELEMENT projetos (projeto)+>
<!ELEMENT projeto (#PCDATA)>
<!ELEMENT data (#PCDATA)>




<!ATTLIST supervisor href CDATA #REQUIRED >
<!ATTLIST email href CDATA #REQUIRED >
<!ATTLIST github href CDATA #REQUIRED >
<!ATTLIST url href CDATA #REQUIRED >
<!ATTLIST projeto href CDATA #REQUIRED >

=== Eddy32/DAW-TPC1/TPC2/ProjRec.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ProjRec SYSTEM "file:/Users/eddy32/Documents/UM/4_Ano/DAW/TPC2/ProjRec.dtd">
<ProjRec>
    <tituloP>My Project Record</tituloP>
    <cabeçalho>
        <nome>TPC2 DAW</nome>
        <titulo>Entrega Trabalho de Desenvolvimento Aplicações WEB</titulo>
        <subtitulo>Utilização de DTD's, XPATH e XML</subtitulo>
        <dataI>24-09-2019</dataI>
        <dataF>01-10-2019</dataF>
        <supervisor href="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
    </cabeçalho>
    <equipa>
        <colaborador> 
            <nomeP>Pedro Jorge Rito Lima</nomeP>
            <numero>a80795</numero>
            <email href="mailto:a80785@alunos.uminho.pt?Subject=Nice">a80785@alunos.uminho.pt</email>
            <github href="https://github.com/Eddy32">GitHub - Eddy32</github>
        </colaborador>
    </equipa>
    <resumo>
        <paragrafo>Entrega do segundo trabalho de casa, da unidade curricular de Desenvolvilmente de Aplicações WEB.</paragrafo>
    </resumo>
    <projetos>
        <projeto href="https://github.com/Eddy32/DAW-TPCs">Repositório dos TPCs</projeto>
    </projetos>
    <data>01-10-2019</data>
</ProjRec>
